SELECT 
C_CUSTKEY AS CUSTOMER_ID,
C_NAME AS CUSTOMER_NUMBER,
C_ADDRESS AS CUSTOMER_ADDRESS,
C_NATIONKEY AS NATION_ID,
C_PHONE AS CUSTOMER_PHONE_NUMBER,
C_ACCTBAL AS CUSTOMER_ACCOUNT_BALANCE,
C_MKTSEGMENT AS CUSTOMER_MARKET_SEGMENT,
C_COMMENT AS CUSTOMER_COMMENT 
FROM 
{{ source('fullscript', 'customer')}}
