SELECT 
O_ORDERKEY AS ORDER_ID,
O_CUSTKEY AS CUSTOMER_ID,
O_ORDERSTATUS AS ORDER_STATUS,
O_TOTALPRICE AS ORDER_TOTAL_PRICE,
O_ORDERDATE AS ORDER_DATE,
O_ORDERPRIORITY AS ORDER_PRIORITY,
O_CLERK AS ORDER_CLERK_NUMBER,
O_SHIPPRIORITY AS ORDER_SHIP_PRIORITY,
O_COMMENT AS ORDER_COMMENT
FROM 
{{ source('fullscript', 'orders')}}
